### ISSUE TITLE
Make each columns scrollable

### ISSUE THREAD

**Issue by kim00kim** [nunof07/bootstrap-collapsible-sidebar#1]
Hello,
I like your approach on making collapsible sidebars, especially with the left and right sidebars. And I'm glad that it's exactly what I need for my project.

I'm just wondering if it's possible to make all columns scrollable, i mean they have their own scrolls? 
Would be better if the browser itself isn't scrollable if there are contents that will make a column longer.

![scrollable-columns](https://user-images.githubusercontent.com/9582956/26964813-d9919fda-4d25-11e7-8c0f-7c2a136c91c1.PNG)

Cheers!

**Comment by nunof07** [comment]
Hi,

Sure, it's possible, but it's outside the scope of this tutorial/project, but feel free to add it yourself.

Here is a tip: add fixed height (probably calculate it dynamically) and `overflow-y: scroll` to `.sidebar`.

Good luck!
